trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  rootDirectory: 'Demo.EventProcessor/Demo.Dapr.EventProcessor.Api'
  dockerRegistryServiceConnection: '35174a8f-edaa-4891-891d-f017c5338f2c'
  dockerImageRepository: 'event-processing/demo-api'
  dockerImageTag: '$(Build.BuildNumber)'

steps:
- task: Docker@2
  displayName: 'Container - Build and push'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(dockerImageRepository)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Demo.EventProcessor/Demo.Dapr.EventProcessor.Api/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/Demo.EventProcessor/'
    tags: |
      $(dockerImageTag)
      latest
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    projects: '**/*.csproj'
    arguments: '--output publish_output --configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: App'
  inputs:
    ArtifactName: App
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Infrastructure'
  inputs:
    PathtoPublish: Infrastructure
    ArtifactName: Infrastructure
