@baseUrl = https://rutzsco-demo-eventp-aca-ci.ambitiousforest-35a763b4.eastus.azurecontainerapps.io
#@baseUrl = http://localhost:49153
### Status 
GET  {{baseUrl}}/status


### Event Sender 
POST  {{baseUrl}}/processtelemetry
content-type: application/json


{
    "data": [
      {
        "name": "Tag1",
        "value": "Value1 "
      }
    ],
    "DelayMS": 10
}
