@baseUrl = https://rutzsco-demo-event-sender.azurewebsites.net/api
### Publish Queue Message

POST {{baseUrl}}/SendEventHubMessageScenarioEndpoint002?code=VotaTknYX4T8BuHm4STuVWAQ40Dona2RaCcZC8zN4bRYAzFul3ZtGQ==
content-type: application/json

{
    "EventModel": {
        "data":[
        {
          "name":"Tag1",
          "value":"Value1 "
          }  ],
        "DelayMS": 
     },
     "Scenario":
     {
         "DurationSeconds": 60, 
         "RatePerSeconds": 2000
     }
 }

